### ISSUE TITLE
Publish the same package, `npx jsr publish` failed (JSR package manifest for 'xxxl' failed to load) but `deno publish` succeeded

### ISSUE THREAD

**Issue by eavidy** [jsr-io/jsr-npm#99]
The problem occurs in this simple example repository: https://github.com/eavidy/edv-test/tree/jsr-bug

deno.json
```
{
  "name": "@asla/vio",
  "version": "0.1.0",
  "exports": "./main.ts"
}
```

main.ts

```ts
import { createSocketCpc } from "jsr:@asn/cpcall@0.6.0";
export { createSocketCpc };
console.log("ok!");

```

My workflow file
```yml
name: pull request
on:
  push:
jobs:
  case1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npx
        continue-on-error: true
        run: npx jsr publish --dry-run

      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: deno
        run: deno publish --dry-run

  case2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: deno
        run: deno publish --dry-run

```
cacse1 and case2 both publish the same package, but case1 fails and case2 succeeds: https://github.com/eavidy/edv-test/actions/runs/9920143639
case1:
![image](https://github.com/user-attachments/assets/355b1058-f5f7-45f7-bd60-93762036beed) 
case2:
![image](https://github.com/user-attachments/assets/2e13eb34-9315-47a2-915b-200cd08f35dc)
